apiVersion: v1
kind: Service
metadata:
  name: {{ include "fleet-app-chart.fullname" . }}
  labels:
    {{- include "fleet-app-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  {{- if eq .Values.service.type "NodePort" }}
    - port: 32080
      targetPort: 32080
      protocol: TCP
      nodePort: {{ .Values.service.ports.nodePort }}
  {{- else }}
    - port: 32080
      targetPort: 32080
      protocol: TCP
      name: nodePort
  {{- end }}
  selector:
    {{- include "fleet-app-chart.selectorLabels" . | nindent 4 }}
